#!/usr/bin/env nodejs
// nodejs script that adds CSV files in current directory into measured.js
var process = require('process');
var fs = require('fs');
var path = require('path');

var measured = {};
var js = [
    '// AV characteristics measured on real diodes or from datasheets',
    '// generated by ./' + path.basename(process.argv[1]),
    '"use strict";',
    'var SC = window.SC || {};',
    'SC.realDiode = SC.realDiode || {};',
    ''
];

fs.readdirSync('.').forEach(filename => {
    var i, lines, va, ext = path.extname(filename);
    if (ext === '.csv') {
        lines = fs.readFileSync(filename, 'utf8').trim().split('\n');
        // remove header volts,amps
        if (lines[0].match(/v/i)) {
            lines.shift();
        }
        // convert to [float, float]
        lines = lines.map(a => {return a.split(',').map(parseFloat).slice(0, 2)});
        // make sure it starts from zero
        //lines.unshift([0, 0]);
        // add diode to measured.js
        js.push('SC.realDiode[' + JSON.stringify(filename.replace(ext, '')) + '] = ' + JSON.stringify(lines) + ';');
        //console.log(lines);
    }
});

fs.writeFileSync('all.js', js.join('\n'), 'utf8');

//console.log(Object.keys(path));
//console.log(JSON.stringify(measured, undefined, 4));